"""Analytical work estimates, not hardware benchmarks. By Juha Vierinen."""
from manim import *
from radial_fft_costs import costs
import re

def cell(s,text,size):
    text=re.sub(r"([0-9.]+)e\+?(-?[0-9]+)",lambda m:m[1]+r"\times10^{"+str(int(m[2]))+"}",text)
    for unit in ["Top/s","Gop","dB"]:text=text.replace(unit,r"\mathrm{"+unit+"}")
    return s.eq(text.replace("%",r"\%"),size)


def cost_slides(s):
    rows=costs()
    s.start('More chirps: more acceleration trials and more total work',
        'Work estimate generated by radial_fft_costs.py, saved in assets/radial_fft_costs.h5. Default bounds .001..3 m, 0..600 m/s, 0..1e6 m/s2; 2 dB full integrated loss; 225 samples/chirp, four RX, 25.37 us chirp spacing. Na from full FMCW derivative bound; G includes velocity-dependent residual correction groups as well as accelerations. Complex radix-two FFT approx 5 L log2 L real arithmetic operations; complex correction multiply 6; scoring16/node. Column union includes invalid trajectories for a conservative FFT column count. Excludes phase/trigonometric generation, memory transfers, integer indexing and final joint refinement. Work per second assumes a new complete bank for every chirp start, not achieved throughput.')
    headers=['Chirps','Acceleration trials','Correction groups','Work / window','Work / second']
    data=[[str(int(r[0])),str(int(r[1])),str(int(r[2])),f'{r[4]/1e9:.3g} Gop',f'{r[5]/1e12:.3g} Top/s'] for r in rows]
    table=Table(data,col_labels=[s.prose(h,24) for h in headers],element_to_mobject=lambda x:cell(s,x,25),h_buff=.5,v_buff=.2,line_config={'color':'#556575','stroke_width':1})
    table.scale_to_fit_width(12).move_to(UP*.65)
    s.play(Create(table),run_time=1.5)
    notes=VGroup(s.prose('Four RX; full default bounds; 2 dB maximum coherent processing loss.',24),
        s.texrow(r'New window every $P=25.37\ \mu\mathrm{s}$: required rate $=W/P$.',24),
        s.prose('Acceleration trials grow roughly with elapsed train duration squared.',23),
        s.prose('Groups also account for velocity-dependent FMCW corrections.',23),
        s.prose('Arithmetic model only: excludes phase generation, transfers and final fit.',21)).arrange(DOWN,buff=.18).move_to(DOWN*2.45)
    s.play(FadeIn(notes));s.wait(1)

    s.start('Relaxing the allowed power loss makes the bank cheaper',
        'Same 16-chirp full default bounds, four RX and analytical operation model. User sets maximum coherent processing loss in dB. The RMS phase bound over all acquired samples includes physical grid spacing, correction sharing and rounded FFT lookup; retained template-overlap power is at least ten to the minus loss-dB over ten. This bounds modeled grid mismatch, not data/model error or runtime. Larger loss coarsens acceleration trials and correction groups.')
    lossrows=[]
    for db in [1,2,3]:
        loss=1-10**(-db/10)
        r=costs(loss,False)[4]
        lossrows.append([f'{db} dB',f'{100*(1-loss):.1f}%',str(int(r[1])),str(int(r[2])),f'{r[5]/1e12:.3g} Top/s'])
    headers=['Allowed coherent loss','Power retained at least','Acceleration trials','Correction groups','Work / second']
    table=Table(lossrows,col_labels=[s.prose(h,22) for h in headers],element_to_mobject=lambda x:cell(s,x,26),h_buff=.4,v_buff=.25,line_config={'color':'#556575','stroke_width':1}).scale_to_fit_width(12).move_to(UP*.7)
    s.play(Create(table),run_time=1.5)
    s.play(Write(s.eq(r'\ell=1-10^{-L_{\rm dB}/10},\qquad |\langle q_{\rm true},q_{\rm bank}\rangle|^2/(\|q_{\rm true}\|^2\|q_{\rm bank}\|^2)\geq1-\ell',36).move_to(DOWN*1.4)))
    notes=VGroup(s.prose('16 chirps, otherwise unchanged bounds and sampling.',25),
        s.prose('One loss budget covers the physical grid, shared corrections and FFT lookup.',23),
        s.prose('Relaxing loss does not remove aliases or guarantee a unique trajectory.',23)).arrange(DOWN,buff=.3).move_to(DOWN*2.6)
    s.play(FadeIn(notes));s.wait(1)
